kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: stolon
  # namespace: stolon-postgres-testing
subjects:
- kind: ServiceAccount
  name: stolon-sa
  # namespace: stolon-postgres-testing
roleRef:
  kind: Role
  name: stolon
  apiGroup: rbac.authorization.k8s.io