apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-nodeport
  namespace: postgres-stolon
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30124  # You can choose any available port in the range 30000-32767
  selector:
    component: stolon-proxy