apiVersion: v1
kind: Pod
metadata:
  name: stolonctl
  # namespace: stolon-postgres-testing
spec:
  serviceAccountName: stolon-sa
  containers:
  - name: stolonctl
    # image: sorintlab/stolon:master-pg15
    image: aayushtheapple/postgres-updated:stolon-postgres-v1.5
    imagePullPolicy: Always
    command: ["/usr/local/bin/stolonctl"]
    args: [
      "--cluster-name=kube-stolon",
      "--store-backend=kubernetes",
      "--kube-resource-kind=configmap",
      "--kube-namespace=postgres-stolon",
      "update",
      "--patch",
      '{
        "pgParameters": {
          "temp_buffers": "2GB",
          "shared_buffers": "20GB",
          "wal_buffers": "200000",
          "work_mem": "2GB",
          "max_connections": "300",
          "max_parallel_workers_per_gather": "6",
          "effective_cache_size": "2GB"
        }
      }'
    ]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - "ALL"
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never