apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stolon-proxy
      stolon-cluster: kube-stolon
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        component: stolon-proxy
        stolon-cluster: kube-stolon
    spec:
      serviceAccountName: stolon-sa
      containers:
      - command:
        - /bin/bash
        - -ec
        - |
          exec gosu stolon stolon-proxy
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STPROXY_CLUSTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['stolon-cluster']
        - name: STPROXY_STORE_BACKEND
          value: kubernetes
        - name: STPROXY_KUBE_RESOURCE_KIND
          value: configmap
        - name: STPROXY_LISTEN_ADDRESS
          value: 0.0.0.0
        - name: STPROXY_METRICS_LISTEN_ADDRESS
          value: 0.0.0.0:8080
        image: aayushtheapple/postgres-updated:stolon-postgres-v1.5
        # image: sorintlab/stolon:master-pg15
        imagePullPolicy: Always
        name: stolon-proxy
        ports:
        - containerPort: 5432
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          tcpSocket:
            port: 5432
          timeoutSeconds: 5
        volumeMounts:
        - name: stolon-secret
          mountPath: /etc/secrets/stolon
          readOnly: true
      # securityContext:
        # runAsUser: 1000
        # fsGroup: 1000
        # runAsUser: 0
      volumes:
      - name: stolon-secret
        secret:
          secretName: stolon
