apiVersion: apps/v1
kind: Deployment
metadata:
  name: stolon-sentinel
spec:
  replicas: 2
  selector:
    matchLabels:
      component: stolon-sentinel
      stolon-cluster: kube-stolon
  template:
    metadata:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        component: stolon-sentinel
        stolon-cluster: kube-stolon
    spec:
      containers:
      - command:
        - /bin/bash
        - -ec
        - |
          exec gosu stolon stolon-sentinel
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STSENTINEL_CLUSTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['stolon-cluster']
        - name: STSENTINEL_STORE_BACKEND
          value: kubernetes
        - name: STSENTINEL_KUBE_RESOURCE_KIND
          value: configmap
        - name: STSENTINEL_METRICS_LISTEN_ADDRESS
          value: 0.0.0.0:8080
        image: aayushtheapple/postgres-updated:stolon-postgres-v1.5
        # image: sorintlab/stolon:master-pg15
        imagePullPolicy: Always
        name: stolon-sentinel
        ports:
        - containerPort: 8080
      # securityContext:
      #   runAsUser: 0
      serviceAccount: stolon-sa
