apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stolon-keeper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: stolon-keeper
      stolon-cluster: kube-stolon
  serviceName: stolon-keeper
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        component: stolon-keeper
        stolon-cluster: kube-stolon
    spec:
      containers:
      - command:
        - /bin/bash
        - -ec
        - |
          # Generate our keeper uid using the pod index
          IFS='-' read -ra ADDR <<< "$(hostname)"
          export STKEEPER_UID="keeper${ADDR[-1]}"
          export POD_IP=$(hostname -i)
          export STKEEPER_PG_LISTEN_ADDRESS=$POD_IP
          export STOLON_DATA=/stolon-data
          chown stolon:stolon $STOLON_DATA
          exec gosu stolon stolon-keeper --data-dir $STOLON_DATA
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STKEEPER_CLUSTER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['stolon-cluster']
        - name: STKEEPER_STORE_BACKEND
          value: kubernetes
        - name: STKEEPER_KUBE_RESOURCE_KIND
          value: configmap
        - name: STKEEPER_PG_REPL_USERNAME
          value: repluser
        - name: STKEEPER_PG_REPL_PASSWORD
          value: replpassword
        - name: STKEEPER_PG_SU_USERNAME
          value: stolon
        - name: STKEEPER_PG_SU_PASSWORDFILE
          value: /etc/secrets/stolon/password
        - name: STKEEPER_METRICS_LISTEN_ADDRESS
          value: 0.0.0.0:8080
        image: aayushtheapple/postgres-updated:stolon-postgres-v1.5
        # image: sorintlab/stolon:master-pg15
        imagePullPolicy: Always
        name: stolon-keeper
        ports:
        - containerPort: 5432
        - containerPort: 8080
        volumeMounts:
        - mountPath: /stolon-data
          name: data
        - mountPath: /etc/secrets/stolon
          name: stolon
      serviceAccount: stolon-sa
      terminationGracePeriodSeconds: 10
      volumes:
      - name: stolon
        secret:
          secretName: stolon
  volumeClaimTemplates:
  - metadata:
      annotations:
        volume.alpha.kubernetes.io/storage-class: standard
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Ti