apiVersion: v1
kind: Pod
metadata:
  name: stolonctl
  # namespace: stolon-postgres-testing
spec:
  serviceAccountName: stolon-sa
  containers:
  - name: stolonctl
    # image: sorintlab/stolon:master-pg15
    image: aayushtheapple/postgres-updated:stolon-postgres-v1.5
    imagePullPolicy: Always
    command: ["/usr/local/bin/stolonctl"]
    args: ["--cluster-name=kube-stolon", "--store-backend=kubernetes", "--kube-resource-kind=configmap", "--kube-namespace=postgres-stolon", "init", "-y"]
    # args: ["--cluster-name=kube-stolon", "--store-backend=kubernetes", "--kube-resource-kind=configmap", "--kube-namespace=<namespace>", "init", "-y"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - "ALL"
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never